version: 1.0.{build}
configuration: Release
platform: x64
before_build:
- cmd: >-
    7z a aeon-stak-cpu-source.zip C:\projects\aeon-stak-cpu\


    git clone -q https://github.com/svn2github/libmicrohttpd build\microhttpd

    cd build\microhttpd\w32\VS2015

    git checkout -qf 82ee737a39be28a32048248655d780ad8a240939

    msbuild libmicrohttpd.sln /property:Configuration=Release-static /property:Platform=x64 /target:libmicrohttpd /verbosity:minimal

    cd ..\..\..\..

    ls C:\projects\aeon-stak-cpu\build\microhttpd\w32\VS2015\Output\x64

    cp C:\projects\aeon-stak-cpu\build\microhttpd\w32\VS2015\Output\x64\libmicrohttpd.lib microhttpd.lib


    curl -o pthreads-w32-2-9-1-release.zip http://www.mirrorservice.org/sites/sources.redhat.com/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip

    7z x -y pthreads-w32-2-9-1-release.zip -oC:\projects\pthreads-w32

    cp C:\projects\pthreads-w32\Pre-built.2\lib\x64\pthreadVC2.lib pthread.lib


    cp C:/OpenSSL-Win64/lib/VC/libeay32MD.lib crypto.lib

    cp C:/OpenSSL-Win64/lib/VC/ssleay32MD.lib ssl.lib


    cmake --version

    cmake -DCMAKE_LIBRARY_PATH="C:\projects\aeon-stak-cpu\build\microhttpd\w32\VS2015\Output\x64" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_FLAGS="/MD" -DCMAKE_CXX_FLAGS_STATIC="/MD" -G "Visual Studio 14 2015 Win64" .
build:
  project: aeon-stak-cpu.sln
  verbosity: minimal
after_build:
- cmd: 7z a aeon-stak-cpu.zip C:\projects\aeon-stak-cpu\bin\RELEASE\aeon-stak-cpu.exe C:\projects\aeon-stak-cpu\config.txt C:/OpenSSL-Win32/*.dll
artifacts:
- path: aeon-stak-cpu.zip
- path: aeon-stak-cpu-source.zip